<?php

/**
 * Implements hook_field_info().
 */
function simple_button_field_field_info() {
  return array(
    'simple_button_field_basic' => array(
      'label' => t('Simple button'),
      'description' => t('Simple button with basic functionality'),
      'default_widget' => 'simple_button_field_basic_button',
      'default_formatter' => 'simple_button_field_basic_button',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function simple_button_field_field_widget_info() {
  return array(
    'simple_button_field_basic_field' => array(
      'label' => t('Basic button'),
      'field types' => array('simple_button_field_basic'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function simple_button_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  switch ($instance['widget']['type']) {
    case 'simple_button_field_basic_field':
      $element['simple_button_basic'] = array(
        '#type' => 'button',
        '#value' => t('Button Text'),
      );
      break;
  }
  return $element;
}

/**
* Implements hook_field_is_empty().
*/
function simple_button_field_field_is_empty($item, $field) {
  if (empty($item['simple_button_basic'])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_field_formatter_info().
 */
function simple_button_field_field_formatter_info() {
  return array(
    'simple_button_field_basic_default' => array(
      'label' => t('Basic button'),
      'field types' => array('simple_button_field_basic'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function simple_button_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'simple_button_field_basic_default':

      break;
    default:
      break;
  }

  return $element;
}

