<?php

/**
 * Implements hook_field_widget_info().
 */
function simple_button_field_field_widget_info() {

}

/**
 * Implements hook_field_widget_form().
 */
function simple_button_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

}

/**
 * Implements hook_field_formatter_info().
 */
function simple_button_field_field_formatter_info() {

}

/**
 * Implements hook_field_formatter_view().
 */
function simple_button_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

}
